"""add buyer account tables

Revision ID: 00acb3271f92
Revises: aa8331f89078
Create Date: 2026-09-04 23:55:44.750471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00acb3271f92'
down_revision: Union[str, Sequence[str], None] = 'aa8331f89078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller-accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller-auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller-accounts_city'), 'seller-accounts', ['city'], unique=False)
    op.create_index(op.f('ix_seller-accounts_country'), 'seller-accounts', ['country'], unique=False)
    op.create_index(op.f('ix_seller-accounts_district'), 'seller-accounts', ['district'], unique=False)
    op.create_index(op.f('ix_seller-accounts_google_place_id'), 'seller-accounts', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_seller-accounts_id'), 'seller-accounts', ['id'], unique=False)
    op.create_index(op.f('ix_seller-accounts_latitude'), 'seller-accounts', ['latitude'], unique=False)
    op.create_index(op.f('ix_seller-accounts_longitude'), 'seller-accounts', ['longitude'], unique=False)
    op.create_index(op.f('ix_seller-accounts_pincode'), 'seller-accounts', ['pincode'], unique=False)
    op.create_index(op.f('ix_seller-accounts_seller_id'), 'seller-accounts', ['seller_id'], unique=True)
    op.create_index(op.f('ix_seller-accounts_state'), 'seller-accounts', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller-accounts_state'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_seller_id'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_pincode'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_longitude'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_latitude'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_id'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_google_place_id'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_district'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_country'), table_name='seller-accounts')
    op.drop_index(op.f('ix_seller-accounts_city'), table_name='seller-accounts')
    op.drop_table('seller-accounts')
    # ### end Alembic commands ###
