"""update buyer saved item table

Revision ID: 16ecff9608dd
Revises: dee6c0321a68
Create Date: 2026-09-06 05:01:51.587753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ecff9608dd'
down_revision: Union[str, Sequence[str], None] = 'dee6c0321a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer_saved_items', sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False))
    op.add_column('buyer_saved_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_buyer_product_saved'), 'buyer_saved_items', type_='unique')
    op.create_unique_constraint('uq_buyer_saved_item', 'buyer_saved_items', ['buyer_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_buyer_saved_item', 'buyer_saved_items', type_='unique')
    op.create_unique_constraint(op.f('uq_buyer_product_saved'), 'buyer_saved_items', ['buyer_id', 'product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('buyer_saved_items', 'updated_at')
    op.drop_column('buyer_saved_items', 'quantity')
    # ### end Alembic commands ###
