"""add buyer saved products

Revision ID: 2430e4f2ec3d
Revises: 16ecff9608dd
Create Date: 2026-09-06 05:26:08.633850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2430e4f2ec3d'
down_revision: Union[str, Sequence[str], None] = '16ecff9608dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_saved_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer-auth.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['seller_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'product_id', name='uq_buyer_saved_product')
    )
    op.create_index(op.f('ix_buyer_saved_products_buyer_id'), 'buyer_saved_products', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_saved_products_id'), 'buyer_saved_products', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_saved_products_product_id'), 'buyer_saved_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_saved_products_product_id'), table_name='buyer_saved_products')
    op.drop_index(op.f('ix_buyer_saved_products_id'), table_name='buyer_saved_products')
    op.drop_index(op.f('ix_buyer_saved_products_buyer_id'), table_name='buyer_saved_products')
    op.drop_table('buyer_saved_products')
    # ### end Alembic commands ###
