"""add seller product table

Revision ID: 345fbb7c36dd
Revises: e463a815b75f
Create Date: 2026-09-05 04:29:35.461708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345fbb7c36dd'
down_revision: Union[str, Sequence[str], None] = 'e463a815b75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('harvest_date', sa.Date(), nullable=True),
    sa.Column('best_before_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_products_category'), 'seller_products', ['category'], unique=False)
    op.create_index(op.f('ix_seller_products_id'), 'seller_products', ['id'], unique=False)
    op.create_index(op.f('ix_seller_products_product_name'), 'seller_products', ['product_name'], unique=False)
    op.create_index(op.f('ix_seller_products_seller_id'), 'seller_products', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_products_status'), 'seller_products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_products_status'), table_name='seller_products')
    op.drop_index(op.f('ix_seller_products_seller_id'), table_name='seller_products')
    op.drop_index(op.f('ix_seller_products_product_name'), table_name='seller_products')
    op.drop_index(op.f('ix_seller_products_id'), table_name='seller_products')
    op.drop_index(op.f('ix_seller_products_category'), table_name='seller_products')
    op.drop_table('seller_products')
    # ### end Alembic commands ###
