"""add buyer orders

Revision ID: 3e08a530f434
Revises: 345fbb7c36dd
Create Date: 2026-09-05 13:08:11.695195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e08a530f434'
down_revision: Union[str, Sequence[str], None] = '345fbb7c36dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=30), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='placed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer-auth.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['seller_products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_auth.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_orders_buyer_id'), 'buyer_orders', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_orders_id'), 'buyer_orders', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_orders_product_id'), 'buyer_orders', ['product_id'], unique=False)
    op.create_index(op.f('ix_buyer_orders_seller_id'), 'buyer_orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_buyer_orders_status'), 'buyer_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_orders_status'), table_name='buyer_orders')
    op.drop_index(op.f('ix_buyer_orders_seller_id'), table_name='buyer_orders')
    op.drop_index(op.f('ix_buyer_orders_product_id'), table_name='buyer_orders')
    op.drop_index(op.f('ix_buyer_orders_id'), table_name='buyer_orders')
    op.drop_index(op.f('ix_buyer_orders_buyer_id'), table_name='buyer_orders')
    op.drop_table('buyer_orders')
    # ### end Alembic commands ###
