"""add seller authentication tables

Revision ID: 6d218b235172
Revises: 
Create Date: 2026-09-04 21:36:45.103763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d218b235172'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller-auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller-auth_email'), 'seller-auth', ['email'], unique=True)
    op.create_index(op.f('ix_seller-auth_id'), 'seller-auth', ['id'], unique=False)
    op.create_index(op.f('ix_seller-auth_is_active'), 'seller-auth', ['is_active'], unique=False)
    op.create_index(op.f('ix_seller-auth_is_email_verified'), 'seller-auth', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_seller-auth_phone'), 'seller-auth', ['phone'], unique=True)
    op.create_table('seller_email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller-auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_email_otps_expires_at'), 'seller_email_otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_seller_email_otps_id'), 'seller_email_otps', ['id'], unique=False)
    op.create_index(op.f('ix_seller_email_otps_is_used'), 'seller_email_otps', ['is_used'], unique=False)
    op.create_index(op.f('ix_seller_email_otps_seller_id'), 'seller_email_otps', ['seller_id'], unique=False)
    op.create_table('seller_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller-auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_sessions_expires_at'), 'seller_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_seller_sessions_id'), 'seller_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_seller_sessions_is_active'), 'seller_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_seller_sessions_seller_id'), 'seller_sessions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_sessions_token_hash'), 'seller_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_sessions_token_hash'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_seller_id'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_is_active'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_id'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_expires_at'), table_name='seller_sessions')
    op.drop_table('seller_sessions')
    op.drop_index(op.f('ix_seller_email_otps_seller_id'), table_name='seller_email_otps')
    op.drop_index(op.f('ix_seller_email_otps_is_used'), table_name='seller_email_otps')
    op.drop_index(op.f('ix_seller_email_otps_id'), table_name='seller_email_otps')
    op.drop_index(op.f('ix_seller_email_otps_expires_at'), table_name='seller_email_otps')
    op.drop_table('seller_email_otps')
    op.drop_index(op.f('ix_seller-auth_phone'), table_name='seller-auth')
    op.drop_index(op.f('ix_seller-auth_is_email_verified'), table_name='seller-auth')
    op.drop_index(op.f('ix_seller-auth_is_active'), table_name='seller-auth')
    op.drop_index(op.f('ix_seller-auth_id'), table_name='seller-auth')
    op.drop_index(op.f('ix_seller-auth_email'), table_name='seller-auth')
    op.drop_table('seller-auth')
    # ### end Alembic commands ###
