"""initial schema

Revision ID: 8057e0379af9
Revises: 
Create Date: 2026-09-05 03:45:11.743944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8057e0379af9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer-auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer-auth_email'), 'buyer-auth', ['email'], unique=True)
    op.create_index(op.f('ix_buyer-auth_id'), 'buyer-auth', ['id'], unique=False)
    op.create_index(op.f('ix_buyer-auth_is_active'), 'buyer-auth', ['is_active'], unique=False)
    op.create_index(op.f('ix_buyer-auth_is_email_verified'), 'buyer-auth', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_buyer-auth_phone'), 'buyer-auth', ['phone'], unique=True)
    op.create_table('seller_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_auth_email'), 'seller_auth', ['email'], unique=True)
    op.create_index(op.f('ix_seller_auth_id'), 'seller_auth', ['id'], unique=False)
    op.create_index(op.f('ix_seller_auth_is_active'), 'seller_auth', ['is_active'], unique=False)
    op.create_index(op.f('ix_seller_auth_is_email_verified'), 'seller_auth', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_seller_auth_phone'), 'seller_auth', ['phone'], unique=True)
    op.create_table('buyer_email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer-auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_email_otps_buyer_id'), 'buyer_email_otps', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_email_otps_expires_at'), 'buyer_email_otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_buyer_email_otps_id'), 'buyer_email_otps', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_email_otps_is_used'), 'buyer_email_otps', ['is_used'], unique=False)
    op.create_table('buyer_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer-auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_sessions_buyer_id'), 'buyer_sessions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_expires_at'), 'buyer_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_id'), 'buyer_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_is_active'), 'buyer_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_token_hash'), 'buyer_sessions', ['token_hash'], unique=True)
    op.create_table('seller_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_accounts_city'), 'seller_accounts', ['city'], unique=False)
    op.create_index(op.f('ix_seller_accounts_country'), 'seller_accounts', ['country'], unique=False)
    op.create_index(op.f('ix_seller_accounts_district'), 'seller_accounts', ['district'], unique=False)
    op.create_index(op.f('ix_seller_accounts_google_place_id'), 'seller_accounts', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_seller_accounts_id'), 'seller_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_seller_accounts_latitude'), 'seller_accounts', ['latitude'], unique=False)
    op.create_index(op.f('ix_seller_accounts_longitude'), 'seller_accounts', ['longitude'], unique=False)
    op.create_index(op.f('ix_seller_accounts_pincode'), 'seller_accounts', ['pincode'], unique=False)
    op.create_index(op.f('ix_seller_accounts_seller_id'), 'seller_accounts', ['seller_id'], unique=True)
    op.create_index(op.f('ix_seller_accounts_state'), 'seller_accounts', ['state'], unique=False)
    op.create_table('seller_email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_email_otps_expires_at'), 'seller_email_otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_seller_email_otps_id'), 'seller_email_otps', ['id'], unique=False)
    op.create_index(op.f('ix_seller_email_otps_is_used'), 'seller_email_otps', ['is_used'], unique=False)
    op.create_index(op.f('ix_seller_email_otps_seller_id'), 'seller_email_otps', ['seller_id'], unique=False)
    op.create_table('seller_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_sessions_expires_at'), 'seller_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_seller_sessions_id'), 'seller_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_seller_sessions_is_active'), 'seller_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_seller_sessions_seller_id'), 'seller_sessions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_sessions_token_hash'), 'seller_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_sessions_token_hash'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_seller_id'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_is_active'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_id'), table_name='seller_sessions')
    op.drop_index(op.f('ix_seller_sessions_expires_at'), table_name='seller_sessions')
    op.drop_table('seller_sessions')
    op.drop_index(op.f('ix_seller_email_otps_seller_id'), table_name='seller_email_otps')
    op.drop_index(op.f('ix_seller_email_otps_is_used'), table_name='seller_email_otps')
    op.drop_index(op.f('ix_seller_email_otps_id'), table_name='seller_email_otps')
    op.drop_index(op.f('ix_seller_email_otps_expires_at'), table_name='seller_email_otps')
    op.drop_table('seller_email_otps')
    op.drop_index(op.f('ix_seller_accounts_state'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_seller_id'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_pincode'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_longitude'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_latitude'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_id'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_google_place_id'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_district'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_country'), table_name='seller_accounts')
    op.drop_index(op.f('ix_seller_accounts_city'), table_name='seller_accounts')
    op.drop_table('seller_accounts')
    op.drop_index(op.f('ix_buyer_sessions_token_hash'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_is_active'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_id'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_expires_at'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_buyer_id'), table_name='buyer_sessions')
    op.drop_table('buyer_sessions')
    op.drop_index(op.f('ix_buyer_email_otps_is_used'), table_name='buyer_email_otps')
    op.drop_index(op.f('ix_buyer_email_otps_id'), table_name='buyer_email_otps')
    op.drop_index(op.f('ix_buyer_email_otps_expires_at'), table_name='buyer_email_otps')
    op.drop_index(op.f('ix_buyer_email_otps_buyer_id'), table_name='buyer_email_otps')
    op.drop_table('buyer_email_otps')
    op.drop_index(op.f('ix_seller_auth_phone'), table_name='seller_auth')
    op.drop_index(op.f('ix_seller_auth_is_email_verified'), table_name='seller_auth')
    op.drop_index(op.f('ix_seller_auth_is_active'), table_name='seller_auth')
    op.drop_index(op.f('ix_seller_auth_id'), table_name='seller_auth')
    op.drop_index(op.f('ix_seller_auth_email'), table_name='seller_auth')
    op.drop_table('seller_auth')
    op.drop_index(op.f('ix_buyer-auth_phone'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_is_email_verified'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_is_active'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_id'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_email'), table_name='buyer-auth')
    op.drop_table('buyer-auth')
    # ### end Alembic commands ###
