"""add buyer authentication tables

Revision ID: aa8331f89078
Revises: 6d218b235172
Create Date: 2026-09-04 22:16:22.187700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8331f89078'
down_revision: Union[str, Sequence[str], None] = '6d218b235172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer-auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer-auth_email'), 'buyer-auth', ['email'], unique=True)
    op.create_index(op.f('ix_buyer-auth_id'), 'buyer-auth', ['id'], unique=False)
    op.create_index(op.f('ix_buyer-auth_is_active'), 'buyer-auth', ['is_active'], unique=False)
    op.create_index(op.f('ix_buyer-auth_is_email_verified'), 'buyer-auth', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_buyer-auth_phone'), 'buyer-auth', ['phone'], unique=True)
    op.create_table('buyer_email_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer-auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_email_otps_buyer_id'), 'buyer_email_otps', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_email_otps_expires_at'), 'buyer_email_otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_buyer_email_otps_id'), 'buyer_email_otps', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_email_otps_is_used'), 'buyer_email_otps', ['is_used'], unique=False)
    op.create_table('buyer_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer-auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_sessions_buyer_id'), 'buyer_sessions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_expires_at'), 'buyer_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_id'), 'buyer_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_is_active'), 'buyer_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_buyer_sessions_token_hash'), 'buyer_sessions', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_sessions_token_hash'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_is_active'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_id'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_expires_at'), table_name='buyer_sessions')
    op.drop_index(op.f('ix_buyer_sessions_buyer_id'), table_name='buyer_sessions')
    op.drop_table('buyer_sessions')
    op.drop_index(op.f('ix_buyer_email_otps_is_used'), table_name='buyer_email_otps')
    op.drop_index(op.f('ix_buyer_email_otps_id'), table_name='buyer_email_otps')
    op.drop_index(op.f('ix_buyer_email_otps_expires_at'), table_name='buyer_email_otps')
    op.drop_index(op.f('ix_buyer_email_otps_buyer_id'), table_name='buyer_email_otps')
    op.drop_table('buyer_email_otps')
    op.drop_index(op.f('ix_buyer-auth_phone'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_is_email_verified'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_is_active'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_id'), table_name='buyer-auth')
    op.drop_index(op.f('ix_buyer-auth_email'), table_name='buyer-auth')
    op.drop_table('buyer-auth')
    # ### end Alembic commands ###
