"""add save for later table

Revision ID: dee6c0321a68
Revises: d24b24cf050d
Create Date: 2026-09-06 02:42:21.983887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee6c0321a68'
down_revision: Union[str, Sequence[str], None] = 'd24b24cf050d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_saved_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer-auth.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['seller_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'product_id', name='uq_buyer_product_saved')
    )
    op.create_index(op.f('ix_buyer_saved_items_buyer_id'), 'buyer_saved_items', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_saved_items_id'), 'buyer_saved_items', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_saved_items_product_id'), 'buyer_saved_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buyer_saved_items_product_id'), table_name='buyer_saved_items')
    op.drop_index(op.f('ix_buyer_saved_items_id'), table_name='buyer_saved_items')
    op.drop_index(op.f('ix_buyer_saved_items_buyer_id'), table_name='buyer_saved_items')
    op.drop_table('buyer_saved_items')
    # ### end Alembic commands ###
