"""add missing seller store table

Revision ID: e463a815b75f
Revises: 8057e0379af9
Create Date: 2026-09-05 03:59:44.226341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e463a815b75f'
down_revision: Union[str, Sequence[str], None] = '8057e0379af9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('store_phone', sa.String(length=20), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('formatted_address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_stores_city'), 'seller_stores', ['city'], unique=False)
    op.create_index(op.f('ix_seller_stores_country'), 'seller_stores', ['country'], unique=False)
    op.create_index(op.f('ix_seller_stores_district'), 'seller_stores', ['district'], unique=False)
    op.create_index(op.f('ix_seller_stores_google_place_id'), 'seller_stores', ['google_place_id'], unique=False)
    op.create_index(op.f('ix_seller_stores_id'), 'seller_stores', ['id'], unique=False)
    op.create_index(op.f('ix_seller_stores_is_active'), 'seller_stores', ['is_active'], unique=False)
    op.create_index(op.f('ix_seller_stores_latitude'), 'seller_stores', ['latitude'], unique=False)
    op.create_index(op.f('ix_seller_stores_longitude'), 'seller_stores', ['longitude'], unique=False)
    op.create_index(op.f('ix_seller_stores_pincode'), 'seller_stores', ['pincode'], unique=False)
    op.create_index(op.f('ix_seller_stores_seller_id'), 'seller_stores', ['seller_id'], unique=False)
    op.create_index(op.f('ix_seller_stores_state'), 'seller_stores', ['state'], unique=False)
    op.create_index(op.f('ix_seller_stores_store_name'), 'seller_stores', ['store_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_stores_store_name'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_state'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_seller_id'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_pincode'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_longitude'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_latitude'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_is_active'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_id'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_google_place_id'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_district'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_country'), table_name='seller_stores')
    op.drop_index(op.f('ix_seller_stores_city'), table_name='seller_stores')
    op.drop_table('seller_stores')
    # ### end Alembic commands ###
